services:
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
